### ISSUE TITLE
HTML test does no longer pass

### ISSUE THREAD

**Issue by sergiomb2** [mquinson/po4a#146]
From po4a-0.54/debian/rules [1]  notice that after same problem on packing it on Fedora ...  `rm t/09-html.t` also fixes the build for me .

[1] 
```
# Remove HTML test, which does no longer pass
# and probably should be removed upstream, too.
override_dh_auto_test:
    rm t/09-html.t
```

**Comment by toddy15** [comment]
Yes, it's probably best to remove the module as well. After all, it was never part of the po4a tarballs, only in the VCS. I've now removed the module as well -- if you don't agree, please feel free to revert this commit:  f8b5288

However, I think we should remove the module, because it's not mature enough and could be easily restored from git, if somebody would like to resume the work.

**Comment by toddy15** [comment]
... oh, by the way, there are two other modules as well: NewsDebian.pm and Debconf.pm. Both are only in git, not in the tarballs -- should they be removed as well?

**Comment by mquinson** [comment]
I completely agree that html should be removed since it is superseeded by xhtml that should work (shouldn't it?).

As for NewsDebian, uhh. It seems that I wrote this 13 years ago :-X I don't remember at all about it... That's a good idea, I should probably make it work at some point. What about moving it to a b0rken/ directory instead of killing it right away?

And Debconf is more complicated. The TransTractor is not enough for this format because all the languages are set in the same translated document. We'd need a way for the formats to say "loop over all languages" or something. Same thing, I'd like to keep this file around, but not with the other modules.

Would you mind if we keep them around?

**Comment by toddy15** [comment]
Certainly not, that's not my call to make. So we'll leave them just in the place where they are. They are in git, but not included in the tarballs. Seems good enough for me. :-)
