### ISSUE TITLE
Adding new LaTeX commands

### ISSUE THREAD

**Issue by MaMaKow** [mquinson/po4a#151]
I started using po4a for the translation of my LaTeX documentation files. For my first try I got reasonably good results.

 But now I got the following error:
```
po4a po4a.conf
documentation_administrator.tex:64: (po4a::tex)
               Unbekannte Umgebung: »lstlisting«
```

I tried to add the following two lines within `/usr/share/perl5/Locale/Po4a/LaTeX.pm`
```
register_generic_command("menu,{_}");
register_generic_command("lstlisting,{}");
```
But it did not change anything.

How can I add new LaTeX commands to po4a?

**Comment by mquinson** [comment]
Hello,

the truth is that I don't know and I suspect that nobody remembers. This module was written by a contributor who disappeared since maybe half a decade. po4a is currently maintained by its users, and I hope that once you figure out how to extend LaTeX.pm, you will contribute back your knowledge to the documentation.

Speaking of which, did you check on [the TeX.pm documentation](https://po4a.org/man/man3/Locale::Po4a::TeX.3pm.php)? It seems to explain how to extend po4a from within the document. If it's what you were looking for, we need to add a pointer from the LateX.pm doc to the TeX.pm doc. If it's not sufficient (as I fear), we need to also extend the TeX.pm documentation.

Thanks for your help and understanding, 
Mt.

**Comment by melvinvermeeren** [comment]
A year later, but the "inline customization" section of Locale::Po4a::TeX(3pm) does correctly explain how to do virtually anything, including commands and environments. If you write the LaTeX sources with po4a in mind everything works very nicely.

po4a 0.55 (Debian buster), man page Locale::Po4a::LaTeX(3pm)

> See the Locale::Po4a::TeX(3pm) manpage for the list of recognized options.

Based upon the above, I think it is safe to close this.

**Comment by mquinson** [comment]
Hello, thanks for the analysis @melvinvermeeren . The documentation of the TeX module is indeed what @MaMaKow needs, and it's linked from the documentation of the LaTeX module. Thus closing.
