### ISSUE TITLE
Asciidoc: old way of writting title triggers a block bug

### ISSUE THREAD

**Issue by Jibec** [mquinson/po4a#239]
Hi, while testing po4a 0.59.1 for Fedora, I noticed this:

Here is my source:

```
= title 1

[source,shell,subs="attributes"]
----
a block

-------------------------------
A content that trigger a po4a bug
-------------------------------

the end of the block
----
= title 2

[source,shell,subs="attributes"]
----
another block line 1
another block line 2

------------------------
Added entries:
------------------------

text 1
text 2
[text 3]
----

text
```

Here is the pot generated by po4a:
```
# SOME DESCRIPTIVE TITLE
# Copyright (C) YEAR Free Software Foundation, Inc.
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2020-05-26 14:25+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#. type: Title =
#: ./index.adoc:1
#, no-wrap
msgid "title 1"
msgstr ""

#. type: delimited block -
#: ./index.adoc:6
#, no-wrap
msgid "a block\n"
msgstr ""

#. type: Plain text
#: ./index.adoc:9
msgid "A content that trigger a po4a bug"
msgstr ""

#. type: delimited block -
#: ./index.adoc:12
#, no-wrap
msgid "the end of the block\n"
msgstr ""

#. type: Title =
#: ./index.adoc:13
#, no-wrap
msgid "title 2"
msgstr ""

#. type: delimited block -
#: ./index.adoc:19
#, no-wrap
msgid ""
"another block line 1\n"
"another block line 2\n"
msgstr ""

#. type: Plain text
#: ./index.adoc:22
msgid "Added entries:"
msgstr ""

#. type: delimited block -
#: ./index.adoc:27
#, no-wrap
msgid ""
"text 1\n"
"text 2\n"
"[text 3]\n"
msgstr ""

#. type: Plain text
#: ./index.adoc:29
msgid "text"
msgstr ""
```

Here is the the diff of po4a output compare to the source:

```
--- index.adoc	2020-05-26 14:20:37.549817281 +0200
+++ out.adoc	2020-05-26 14:23:46.917896976 +0200
@@ -1,12 +1,12 @@
 = title 1
 
-[source,shell,subs="attributes"]
+[source, shell, subs="attributes"]
 ----
 a block
 
 -------------------------------
 A content that trigger a po4a bug
--------------------------------
+---------------------------------
 
 the end of the block
 ----
@@ -14,15 +14,13 @@
 
 [source,shell,subs="attributes"]
 ----
-another block line 1
-another block line 2
+another block line 1 another block line 2
 
 ------------------------
 Added entries:
 ------------------------
 
-text 1
-text 2
+text 1 text 2
 [text 3]
 ----
```

If I remove a few dashes around "A content that trigger a po4a bug", here is the generated pot:
```
# SOME DESCRIPTIVE TITLE
# Copyright (C) YEAR Free Software Foundation, Inc.
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2020-05-26 14:33+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#. type: Title =
#: ./index.adoc:1
#, no-wrap
msgid "title 1"
msgstr ""

#. type: delimited block -
#: ./index.adoc:6
#, no-wrap
msgid "a block\n"
msgstr ""

#. type: Plain text
#: ./index.adoc:9
msgid "A content that trigger a po4a bug"
msgstr ""

#. type: delimited block -
#: ./index.adoc:12
#, no-wrap
msgid "the end of the block\n"
msgstr ""

#. type: Title =
#: ./index.adoc:13
#, no-wrap
msgid "title 2"
msgstr ""

#. type: delimited block -
#: ./index.adoc:19
#, no-wrap
msgid ""
"another block line 1\n"
"another block line 2\n"
msgstr ""

#. type: Plain text
#: ./index.adoc:22
msgid "Added entries:"
msgstr ""

#. type: delimited block -
#: ./index.adoc:27
#, no-wrap
msgid ""
"text 1\n"
"text 2\n"
"[text 3]\n"
msgstr ""

#. type: Plain text
#: ./index.adoc:29
msgid "text"
msgstr ""
```

And the diff returns to normal:
```
--- index.adoc	2020-05-26 14:25:30.001864403 +0200
+++ out.adoc	2020-05-26 14:25:44.657717610 +0200
@@ -1,6 +1,6 @@
 = title 1
 
-[source,shell,subs="attributes"]
+[source, shell, subs="attributes"]
 ----
 a block
 
@@ -12,7 +12,7 @@
 ----
 = title 2
 
-[source,shell,subs="attributes"]
+[source, shell, subs="attributes"]
 ----
 another block line 1
 another block line 2
```

Expected: the carriage returns must remain because it impacts asciidoc rendering

**Comment by jnavila** [comment]
Asciidoctor request that delimiters length be matched.

Asciidoctor User's manual:
> The AsciiDoc Python processor did not require the delimiters to be balanced, but also never documented that this was permissible. We view AsciiDoc Python’s behavior of matching unbalanced delimited blocks to be a bug and therefore do not allow it in Asciidoctor.

I also thing it's saner and would completely remove the class of bugs that you are seeing.

**Comment by Jibec** [comment]
Do you mean there is an error in source content?

**Comment by jnavila** [comment]
I just mean that according to the citation, plain old python asciidoc toolchain would generate output by interpreting source content the same way it is actually interpreted by po4a. But, with Asciidoctor's behavior, the content would be interpreted the way we, human, understand it. And I think Asciidoctor's logic is saner.

**Comment by jnavila** [comment]
@mquinson  Should we require stringent length equality between opening and closing fences?

On one hand, this would solve this bug. OTOH that may break existing projects.

**Comment by mquinson** [comment]
I would prefer if po4a would remain less strict than the other parsers, if it would accept even almost-correct inputs. In the manpages, po4a can even fix some small issues on the fly, where the normalized version contains less errors than the original one in some cases.

That's my opinion, but it's a bit hard to say for sure since I'm not the one writing the code right now...

**Comment by jnavila** [comment]
I just wanted you philosophy on how to parse almost incorrect input. Thanks.

So, this will be managed by another option, I guess.

**Comment by ciampix** [comment]
> I would prefer if po4a would remain less strict than the other parsers, if it would accept even almost-correct inputs. In the manpages, po4a can even fix some small issues on the fly, where the normalized version contains less errors than the original one in some cases.

I strongly agree with you, but it should be nice that when such corrections are in place asciidoc would emit some kind of warnings...

**Comment by jnavila** [comment]
Asciidoc is not a stringly syntactically typed markup language, so you can never know what was the intention of the writer.

I still don't think this is the role of po4a. This `compat` option add stricter rules in the parsing but they cannot detect incorrect input, or even cope with creative uses of the `include` directive. For me, this can only be done in a renderer such as asciidoc or asciidoctor where you have the whole file in its final state and you can perform some basic health tests. You can for instance:

 * report missing third party files or includes
 * detect that the file is finished while still in a fenced block
 * detect internal links to non-existent anchors
 * detect inline formatting not closed at the end of a paragraph

**Comment by Jibec** [comment]
Thanks a lot to both of you.
--
Jean-Baptiste

**Comment by mquinson** [comment]
I agree that we cannot (and should not) try to enforce any kind of conformance to whatever. If the input is broken and the translated doc is equally broken (as much as the input, preferably not more than the input), that's perfectly fine. po4a is not an asciidoc linter.  That's not our purpose.

What I mean is that po4a should use defensive programming and be cautious about its input. The difficulty is that po4a is a technical attempt to solve a social issue, ie the collaboration between doc writers, translators, and end users that don't speak English. 

If po4a is too picky about the input format, doc writers will disregard po4a's error messages, which is never good. Same if the error messages are not specific enough, and that's why I like very much the compat new option. It gives us the ability to produce highly specialized feedback.

But if it produces invalid translated files, the whole l10n process will be disabled from the build chain. So there is another source of concern: po4a should try to prevent the translators from introducing formatting errors. This is why po4a introduces the markdown-text tag, so that we can benefit from the weblate checks that are specific to that language (patches to integrate them [partially] into po4a directly would be gladly accepted). For the groff plugin (man pages), similar checks are integrated into po4a directly. 

I don't think we have any check of the translation in asciidoc. #242 is somewhat related to this problem, but not completely.

**Comment by jnavila** [comment]
> But if it produces invalid translated files, the whole l10n process will be disabled from the build chain. So there is another source of concern: po4a should try to prevent the translators from introducing formatting errors. This is why po4a introduces the markdown-text tag, so that we can benefit from the weblate checks that are specific to that language (patches to integrate them [partially] into po4a directly would be gladly accepted). For the groff plugin (man pages), similar checks are integrated into po4a directly.

That is another story and I fully agree with you, from experience. Even when segmentation has been done to free translators from block-level markup errors, we still face a risk that inline markup be upset by translators, such as styles and anchors. To be able to interact with professional translators, we had to add some rules in their translation framework in order to correctly tag, preserve and check inline formattings. IMAO, this is clearly a missing feature of po oriented tools that do not provide such customizations the way they provide checks for c-style place-holders and so on.

Maybe po4a could provide some sanity check on this, such as check that links are correctly preserved. Right now, I can perform the check after generation of an html file (using https://github.com/gjtorikian/html-proofer), this is still a late and loose check.

**Comment by ciampix** [comment]
I IMHO think that asciidoc(tor) should have a sanity check instead of po4a. I will post a feature request on this regard on both project (asciidoc & asciidoctor) if absent. THEN po4a could be able to check the presence of asciidoc(tor) compiler and fire a sanity check first on demand...
