### ISSUE TITLE
Asciidoc: add an option to prevent line wrapping

### ISSUE THREAD

**Issue by jnavila** [mquinson/po4a#242]
If a paragraph of a list item contains for instance "see point A. Bla bla bla" and the wrapping occurs like that:

```
  see point 
  A. Bla bla bla
```

Then the second line can be interpreted as a sub-list start. Disabling wrapping would ensure that such occurence does not happen.

If asciidoc output is aimed at being read directly, wrapping might still be an option. But for machine processing, it's safer to disable it.

**Comment by mquinson** [comment]
That's an important issue, because I don't see any good solution. The less bad would be to prevent rewrapping all together as you propose, and I don't see how we could wrap the content while avoiding such issue.

I guess that a "neverwrap" as in the Text module is the way to go, at the end. 

Thanks,
