### ISSUE TITLE
manpage-l10n: Untranslated text in man pages, here soelim(1)

### ISSUE THREAD

**Issue by hmartink** [mquinson/po4a#288]
Hello,
I'm one of the maintainers of manpages-l10n, which has a huge body of man pages translated, using po4a. While the very vast majority does convert fine and without problems, a few pages do not. I'm trying to track those down and fix them where possible. Ideally the fix would be in po4a, but I can also contact the respective upstream to fix the source pages (but of course I don't know if they will do it).

I'm reporting here, but if an e-mail channel would be available for discussing these failures, this would be great.

The first example is soelim(1) from the groff package. In the rendered man page you see some kind of primitive graphics. However, those strings are not contained when the po file is created and thus cannot be translated.

I can provide you with the man pot file and the original man page if you want, unfortunately github won't let me add them (just gives me an error message), even if I zip them. Apologies.

**Comment by mquinson** [comment]
Hello, thanks for the report.

Could you please provide links to the faulty pages? The best would be a patch or a pull request to po4a adding these files to https://github.com/mquinson/po4a/tree/master/t/fmt/man The other files in this directory give an example of what we use as test cases. 

For a given test, the `.man` file is the input. The `.norm` file is the same file once processed by po4a with no translation provided. The `pot` file is what po4a should provide, The `po` file is provided to po4a to produce the `trans` file. To ease the maintainance of po4a to people not speaking foreign languages, the convention is to use uppercase as a translation in the `po` file. Once written, the test has to be added to https://github.com/mquinson/po4a/blob/master/t/fmt-man.t After that, check the CONTRIBUTING.md file about how to run the tests. The expected behavior in your case is to have the added test to fail until the code is fixed.

If you can provide us with easy to use test cases, I have good chances of managing to fix the issues in the source code. Without these test cases, that's ways more work for me, as I first need to finely understand the issue.

Thanks in advance,
Mt.

**Comment by Fat-Zer** [comment]
You are likely looking for the `groff_code` option of the `man` module. You should set it to `translate` to make the ASCII-graphic from within the `.ie` directive appear inside your PO files... Just add `-o "groff_code=translate"` to the po4a scripts and rebuild your translation files. See [`man Locale::Po4a::Man`](https://po4a.org/man/man3/Locale::Po4a::Man.3pm.php) for details.

PS: There is also a maillist and an IRC channel if you prefer other forms of communication rather than github, see https://po4a.org/getinvolved.php . Both are not very active but still alive.

**Comment by hmartink** [comment]
Hello Martin,
hello Fat-Zer,
we'll try out the groff_code option and I report here if that was the missing piece. If not, I'll post appropriate links here.
And thanks for the pointer to the maillist, much easier than these web based trackers.

**Comment by mariobl** [comment]
Indeed, the option »groff_code=translated« works, at least for the man page of soelim(1). Currently we use »groff_code=verbatim«. I will test it with other man pages. Thanks for the hint.

**Comment by mquinson** [comment]
It seems that this issue is solved. Feel free to reopen, or to open a new one if you encounter other issues.
