### ISSUE TITLE
[feature] YODL

### ISSUE THREAD

**Issue by Freed-Wu** [mquinson/po4a#403]
[The doc of zsh](https://github.com/zsh-users/zsh/tree/master/Doc) uses [YODL](https://www.w3.org/Tools/YODL.html). Does po4a support it?

**Comment by mquinson** [comment]
Hello,

I never heard of YODL until now, so no, there is not support of this format in po4a so far, sorry. I spent some time reading the zsh documentation under that format, and it seems interesting. Is this file format widely used, or is it limited to zsh? It's actually rather advanced and building a parser for po4a would certainly be doable, but not completely trivial. If you're interested in contributing such parser, I could guide you in the process, but I will not have the time to dig into this task myself, sorry about that.

Thanks for bringing this format to my attention,
Mt

**Comment by Freed-Wu** [comment]
> The doc of zsh uses YODL. Does po4a support it?

Oh, I am not familiar with YODL and I just want to know if po4a can support it so the translators can face po/mo not unfamiliar YODL. Thanks for your answer!

**Comment by mquinson** [comment]
@Freed-Wu what's your practical interest in this format? Would you consider contributing a YODL module for po4a?

**Comment by Freed-Wu** [comment]
Oh, temporarily I don't have enough time. When I am free, I'll take a look.

**Comment by mquinson** [comment]
Hello @Freed-Wu,

I'm closing this bug because I do not consider adding this feature myself for the time being. I would love to assist you if you plan to implement this support yourself. You wil find more information about the internals of po4a and how to implement a new parser in po4a in this document: https://github.com/mquinson/po4a/blob/master/doc/po4a.7.pod#transtractors-and-project-architecture  

Please reopen and comment if you want to go that way.

Thanks for reporting,
Mt
