### ISSUE TITLE
Can po4a handle the Doxygen's Source Files, *.doc?

### ISSUE THREAD

**Issue by hwhsu1231** [mquinson/po4a#430]
I saw `master.doc` in the help message of `po4a-gettextize --help`:

```cmd
C:\Users\hwhsu1231>po4a-gettextize --help
Usage:
    po4a-gettextize -f fmt -m master.doc -l XX.doc -p XX.po

    (XX.po is the output, all others are inputs)

Options:
    -f, --format
        Format of the documentation you want to handle. Use the
        --help-format option to see the list of available formats.
```

I remember that Doxygen uses this `.doc` extention as well. Does it mean that po4a is able to handle the Doxygen's Source Files, `*.doc`?

**Comment by mquinson** [comment]
Unfortunately not. po4a cannot handle doxygen source files for now. This is just an example. The supported formats are listed from https://po4a.org/

That being said, I'm not sure of what kind of support we are speaking of. Which doc source file are you speaking of? Doxygen can be used to document many programing languages, and I think it comes with more than syntax format. Could you please be more explicit?

Thanks for your interest,

**Comment by mquinson** [comment]
Hello @hwhsu1231,

as noted, po4a is not supporting Doxygen files for now. I'm closing this bug because I do not consider adding this feature myself for the time being. I would love to assist you if you plan to implement this support yourself. You wil find more information about the internals of po4a and how to implement a new parser in po4a in this document: https://github.com/mquinson/po4a/blob/master/doc/po4a.7.pod#transtractors-and-project-architecture  

Please reopen and comment if you want to go that way.

Thanks for reporting,
Mt
