### ISSUE TITLE
Failed to run 'po4a-gettextize' for 'sgml' format (Error while running onsgmls -p)

### ISSUE THREAD

**Issue by hwhsu1231** [mquinson/po4a#489]
### Problem Description

Recently, I tried to use `po4a-gettextize` to generate po files for SGML of PostgresSQL, but failed with the following error messages:

```bash
hwhsu1231@vb-kubuntu:~/Repo/testing/postgres/doc/src/sgml$ po4a-gettextize -f sgml -m xtypes.sgml -p xtypes.po
onsgmls:/tmp/po4a-5Oq6.sgml:3:1:E: prolog can't be omitted unless CONCUR NO and LINK EXPLICIT NO and either IMPLYDEF ELEMENT YES or IMPLYDEF DOCTYPE YES
onsgmls:/tmp/po4a-5Oq6.sgml:3:1:E: no document type declaration; will parse without validation
po4a::sgml: Error while running onsgmls -p.  Please check if onsgmls and the DTD are installed.
hwhsu1231@vb-kubuntu:~/Repo/testing/postgres/doc/src/sgml$
```

What happened?

### Version and Platform

* OS version: Kubuntu 22.04
* po4a version: `0.66`

**Comment by Fat-Zer** [comment]
There are two problems:

1. For sgml you should specify only the root document, rather than those it includes, for postgres it should be `postges.sgml`.
2. Despite the extensions, the files seems to be in xml docbook format (as the `Makefile`s use xsltproc to process them) rather than actual sgml. So you'd have better luck using `docbook` module:

       po4a-gettextize -f docbook -m xtypes.sgml -p xtypes.po

PS: You're using quite old version of po4a, so I'm not sure how things were back then, but nowadays you should use `po4a-updatepo` to generate pot-files rather than `po4a-gettextize`, or even better the unified `po4a` utility.

**Comment by mquinson** [comment]
I'm closing this issue because @Fat-Zer provided an explanation to the initial answer. Thanks for that.

@hwhsu1231 do not hesitate to reopen this bug with additional information if this does not solve the problem for you.
