### ISSUE TITLE
Fails to build with perl 5.40

### ISSUE THREAD

**Issue by stoecker** [mquinson/po4a#508]
See here:  https://build.opensuse.org/public/build/devel:languages:perl/openSUSE_Tumbleweed/x86_64/po4a/_log

Most tests fail with
Attempt to call undefined import method with arguments ("process" ...) via package "Locale::Po4a::TransTractor"

**Comment by mlschroe** [comment]
(The tests fail because perl-5.40 prints the above warning message).

Background is that perl upstream deprecated usage of `UNIVERSAL::import`. Usually, `import()` comes from the Exporter module, but TransTractor.pm does a `require Exporter` without having `Exporter` in the ISA list, so the `import` function does not get defined. This is probably also true for a couple of other modules. 

Adding a `sub import {}l` to TransTractor.pm fixes the build but is most likely not the correct thing to do.

**Comment by ana** [comment]
Hi @mquinson

@mlschroe submitted this patch to openSUSE Tumbleweed and the distribution switched to perl 5.40 with no issues last week. You have the full changeset at:
https://build.opensuse.org/request/show/1184865

The part you want is the one line patch:

```
--- lib/Locale/Po4a/TransTractor.pm.orig	2024-07-02 11:29:25.396972130 +0000
+++ lib/Locale/Po4a/TransTractor.pm	2024-07-02 11:29:48.916941692 +0000
@@ -5,6 +5,8 @@ require Exporter;
 package Locale::Po4a::TransTractor;
 use DynaLoader;
 
+sub import {};
+
 use 5.16.0;
 use strict;
 use warnings;

```
